const fs = require('fs-extra');
const path = require('path');
const uppercamelize = require('uppercamelcase');

const pkg = require('../package.json');

const version = process.env.VERSION || pkg.version;
const tips = '// This file is auto generated by build/build-entry.js';

const Components = require('./get-components')();

function buildComponents() {
  const exportList = Components.map(name => `export { default as ${uppercamelize(name)} } from './${name}';`);
  const content = `${tips}
${exportList.join('\n')}
`;
  fs.writeFileSync(path.join(__dirname, '../src/components.js'), content);
}

function buildCSSEntry() {
  const importList = Components.map(name => `@import './${name}.less';`);
  const content = `${tips}
@import './animations/index.less';

${importList.join('\n')}
`;
  fs.writeFileSync(path.join(__dirname, '../src/style/index.less'), content);
}

function bulidVersion() {
  const content = `
// This file is auto generated by build/build-entry.js
export const version = '${version}';
`;
  fs.writeFileSync(path.join(__dirname, '../site/version.js'), content);
}

buildComponents();
buildCSSEntry();
bulidVersion();
